import type { Metadata } from "next";
import {Roboto} from 'next/font/google'
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/layout/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-7xl m-auto p-4">
        <Header/>
        {children}
        <footer className="border-t p-8 text-center text-gray-500 mt-16">
      &copy; 2024 All rights reserved
    </footer>
        </main>
      </body>
    </html>
  );
}
